import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>OpenSea Blockchain-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-green-900 flex flex-col items-center justify-center font-bold text-3xl w-full h-screen">
        <h1 className="">BrainGhost</h1>
        <h1 className="underline">Hello world!</h1>
      </main>
    </div>
  );
}
