import { useWeb3 } from "@3rdweb/hooks";
import Head from "next/head";
import { useEffect } from "react";
import toast, { Toaster } from "react-hot-toast";
import Header from "../components/Header";
import Hero from "../components/Hero";
import { client } from "../lib/sanityClient";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { address, connectWallet } = useWeb3();
  const welcomeUser = (userName, toastHandler = toast) => {
    toastHandler.success(
      `Welcome back ${userName !== "unnamed" ? `${userName}` : ""}!`,
      {
        style: {
          background: "#04111d",
          color: "#fff",
        },
      }
    );
  };

  const style = {
    wrapper: ` `,
    walletConnectWrapper: ` bg-[#202225] flex flex-col justify-center items-center h-screen bg-[#3b3d42]`,
    button: `border border-[#282b2f] bg-[#2181e2]  text-gray-200 hover:bg-[#42a0ff] p-[0.8rem] text-xl font-semibold rounded-lg cursor-pointer`,
    details: `text-lg text-center text-[#99a1a8] mt-4`,
  };
  useEffect(() => {
    if (!address) return;
    (async () => {
      const userDoc = {
        _type: "users",
        _id: address,
        userName: "Unnamed",
        walletAddress: address,
      };
      const result = await client.createIfNotExists(userDoc);
      welcomeUser(result.userName);
    })();
  }, [address]);

  return (
    <div className={styles.container}>
      <Head>
        <title>OpenSea Blockchain-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <Toaster position="top-center" reverseOrder={false} />
      {address ? (
        <main className="">
          <Header />
          <Hero />
        </main>
      ) : (
        <div className="wrapper">
          <div className={style.walletConnectWrapper}>
            <button
              className={style.button}
              onClick={() => connectWallet("injected")}
            >
              Metamask - Connet Wallet
            </button>
            <div className={style.details}>
              You need chrome to be <br /> able to run this app
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
